(lang dune 3.22)

(name chyron)

(generate_opam_files true)

(source
 (github jamessouth/chyron))

(authors "James D. South")

(maintainers "James D. South")

(license GPL3)

(documentation https://github.com/jamessouth/chyron/blob/master/README.md)

(package
 (name chyron)
 (synopsis "text scroller/ticker/chyron")
 (description "a text scroller/ticker for polybar, etc.")
 (depends ocaml dune core)
 (tags ("scroll ticker chyron")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
