(lang dune 3.22)

(name chyron)

(generate_opam_files true)

(source
 (github jamessouth/chyron))

(authors "James D. South")

(maintainers "James D. South")

(license GPL3)

(documentation https://github.com/jamessouth/chyron/blob/master/README.md)

(package
 (name chyron)
 (synopsis "text scroller/ticker/chyron")
 (description "a text scroller/ticker for polybar, etc.")
 (depends
  ocaml
  dune
  core
  ppx_jane
  core_unix
  ppx_inline_test
  ppx_deriving
  ppx_assert
  qcheck-core
  uuseg)
 (tags ("scroll ticker chyron")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
; (depends ocaml dune base core ppx_jane core_unix ocaml-lsp-server ocamlformat odoc ppx_inline_test utop ppx_deriving ppx_assert qcheck-core)
